#Analisis exploratorio de los datos de satelites Starlink extraidos de la API de Space-X. Hay una relación entre los parametros de orbita y el tiempo que un satelite permanece en orbita / la salida del orbite de un satelite?

In [ ]:
#import libraries

import pandas as pd
import numpy as np
import os
import requests
import datetime
import matplotlib.pyplot as plt
from matplotlib import ticker

import seaborn as sns
sns.set()


import warnings
warnings.filterwarnings("ignore")

In [ ]:
#save URL for API call and the output from the API

url_starlink_sats = 'https://api.spacexdata.com/v4/starlink'
res_starlink_sats = requests.get(url = url_starlink_sats)
satellites = res_starlink_sats.json()

In [3]:
satellites

[{'spaceTrack': {'CCSDS_OMM_VERS': '2.0',
   'COMMENT': 'GENERATED VIA SPACE-TRACK.ORG API',
   'CREATION_DATE': '2020-10-13T04:16:08',
   'ORIGINATOR': '18 SPCS',
   'OBJECT_NAME': 'STARLINK-30',
   'OBJECT_ID': '2019-029K',
   'CENTER_NAME': 'EARTH',
   'REF_FRAME': 'TEME',
   'TIME_SYSTEM': 'UTC',
   'MEAN_ELEMENT_THEORY': 'SGP4',
   'EPOCH': '2020-10-13T02:56:59.566560',
   'MEAN_MOTION': 16.43170483,
   'ECCENTRICITY': 0.0003711,
   'INCLINATION': 52.9708,
   'RA_OF_ASC_NODE': 332.0356,
   'ARG_OF_PERICENTER': 120.7278,
   'MEAN_ANOMALY': 242.0157,
   'EPHEMERIS_TYPE': 0,
   'CLASSIFICATION_TYPE': 'U',
   'NORAD_CAT_ID': 44244,
   'ELEMENT_SET_NO': 999,
   'REV_AT_EPOCH': 7775,
   'BSTAR': 0.0022139,
   'MEAN_MOTION_DOT': 0.47180237,
   'MEAN_MOTION_DDOT': 1.2426e-05,
   'SEMIMAJOR_AXIS': 6535.519,
   'PERIOD': 87.635,
   'APOAPSIS': 159.809,
   'PERIAPSIS': 154.958,
   'OBJECT_TYPE': 'PAYLOAD',
   'RCS_SIZE': 'LARGE',
   'COUNTRY_CODE': 'US',
   'LAUNCH_DATE': '2019-05-24',
   'SITE': 'AFETR',
   'DECAY_DATE': '2020-10-13',
   'DECAYED': 1,
   'FILE': 2850561,
   'GP_ID': 163365918,
   'TLE_LINE0': '0 STARLINK-30',
   'TLE_LINE1': '1 44244U 19029K   20287.12291165  .47180237  12426-4  22139-2 0  9995',
   'TLE_LINE2': '2 44244  52.9708 332.0356 0003711 120.7278 242.0157 16.43170483 77756'},
  'launch': '5eb87d30ffd86e000604b378',
  'version': 'v0.9',
  'height_km': None,
  'latitude': None,
  'longitude': None,
  'velocity_kms': None,
  'id': '5eed770f096e59000698560d'},
 {'spaceTrack': {'CCSDS_OMM_VERS': '2.0',
   'COMMENT': 'GENERATED VIA SPACE-TRACK.ORG API',
   'CREATION_DATE': '2020-09-28T19:26:08',
   'ORIGINATOR': '18 SPCS',
   'OBJECT_NAME': 'STARLINK-74',
   'OBJECT_ID': '2019-029BL',
   'CENTER_NAME': 'EARTH',
   'REF_FRAME': 'TEME',
   'TIME_SYSTEM': 'UTC',
   'MEAN_ELEMENT_THEORY': 'SGP4',
   'EPOCH': '2020-09-28T18:35:08.710368',
   'MEAN_MOTION': 16.29892189,
   'ECCENTRICITY': 0.0002076,
   'INCLINATION': 52.9971,
   'RA_OF_ASC_NODE': 48.1405,
   'ARG_OF_PERICENTER': 323.1313,
   'MEAN_ANOMALY': 37.5805,
   'EPHEMERIS_TYPE': 0,
   'CLASSIFICATION_TYPE': 'U',
   'NORAD_CAT_ID': 44293,
   'ELEMENT_SET_NO': 999,
   'REV_AT_EPOCH': 7653,
   'BSTAR': 0.0024534,
   'MEAN_MOTION_DOT': 0.1135935,
   'MEAN_MOTION_DDOT': 1.2115e-05,
   'SEMIMAJOR_AXIS': 6570.966,
   'PERIOD': 88.349,
   'APOAPSIS': 194.195,
   'PERIAPSIS': 191.467,
   'OBJECT_TYPE': 'PAYLOAD',
   'RCS_SIZE': 'LARGE',
   'COUNTRY_CODE': 'US',
   'LAUNCH_DATE': '2019-05-24',
   'SITE': 'AFETR',
   'DECAY_DATE': '2020-09-29',
   'DECAYED': 1,
   'FILE': 2837086,
   'GP_ID': 162391575,
   'TLE_LINE0': '0 STARLINK-74',
   'TLE_LINE1': '1 44293U 19029BL  20272.77440637  .11359350  12115-4  24534-2 0  9995',
   'TLE_LINE2': '2 44293  52.9971  48.1405 0002076 323.1313  37.5805 16.29892189 76534'},
  'launch': '5eb87d30ffd86e000604b378',
  'version': 'v0.9',
  'height_km': None,
  'latitude': None,
  'longitude': None,
  'velocity_kms': None,
  'id': '5eed770f096e59000698560e'},
 {'spaceTrack': {'CCSDS_OMM_VERS': '2.0',
   'COMMENT': 'GENERATED VIA SPACE-TRACK.ORG API',
   'CREATION_DATE': '2020-10-13T17:46:09',
   'ORIGINATOR': '18 SPCS',
   'OBJECT_NAME': 'STARLINK-29',
   'OBJECT_ID': '2019-029J',
   'CENTER_NAME': 'EARTH',
   'REF_FRAME': 'TEME',
   'TIME_SYSTEM': 'UTC',
   'MEAN_ELEMENT_THEORY': 'SGP4',
   'EPOCH': '2020-10-13T17:09:39.946752',
   'MEAN_MOTION': 16.50981164,
   'ECCENTRICITY': 0.0008105,
   'INCLINATION': 52.9786,
   'RA_OF_ASC_NODE': 228.8138,
   'ARG_OF_PERICENTER': 330.1078,
   'MEAN_ANOMALY': 31.0927,
   'EPHEMERIS_TYPE': 0,
   'CLASSIFICATION_TYPE': 'U',
   'NORAD_CAT_ID': 44243,
   'ELEMENT_SET_NO': 999,
   'REV_AT_EPOCH': 7928,
   'BSTAR': 0.00010982,
   'MEAN_MOTION_DOT': 0.11982673,
   'MEAN_MOTION_DDOT': 1.2791e-05,
   'SEMIMAJOR_AXIS': 6514.89,
   'PERIOD': 87.22,
   'APOAPSIS': 142.035,
   'PERIAPSIS': 131.474,
   'OBJECT_TYPE': 'PAYLOAD',
   'RCS_SIZE': 'LARGE',
   'COUNTRY_CODE': 'US',
   'LAUNCH_DATE': '2019-05-24',
   'SITE': 'AFETR',
   'DECAY_DATE': '2020-10-13',
   'DECAYED': 1,
   'FILE': 2851295,
   'GP_ID': 163381397,
   'TLE_LINE0': '0 STARLINK-29',
   'TLE_LINE1': '1 44243U 19029J   20287.71504568  .11982673  12791-4  10982-3 0  9997',
   'TLE_LINE2': '2 44243  52.9786 228.8138 0008105 330.1078  31.0927 16.50981164 79283'},
  'launch': '5eb87d30ffd86e000604b378',
  'version': 'v0.9',
  'height_km': None,
  'latitude': None,
  'longitude': None,
  'velocity_kms': None,
  'id': '5eed770f096e59000698560f'},
 {'spaceTrack': {'CCSDS_OMM_VERS': '2.0',
   'COMMENT': 'GENERATED VIA SPACE-TRACK.ORG API',
   'CREATION_DATE': '2021-09-26T14:36:11',
   'ORIGINATOR': '18 SPCS',
   'OBJECT_NAME': 'STARLINK-76',
   'OBJECT_ID': '2019-029BE',
   'CENTER_NAME': 'EARTH',
   'REF_FRAME': 'TEME',
   'TIME_SYSTEM': 'UTC',
   'MEAN_ELEMENT_THEORY': 'SGP4',
   'EPOCH': '2021-09-26T14:04:34.023360',
   'MEAN_MOTION': 16.43523148,
   'ECCENTRICITY': 0.0003663,
   'INCLINATION': 52.9578,
   'RA_OF_ASC_NODE': 116.726,
   'ARG_OF_PERICENTER': 96.3451,
   'MEAN_ANOMALY': 319.5267,
   'EPHEMERIS_TYPE': 0,
   'CLASSIFICATION_TYPE': 'U',
   'NORAD_CAT_ID': 44287,
   'ELEMENT_SET_NO': 999,
   'REV_AT_EPOCH': 13263,
   'BSTAR': 0.0014077,
   'MEAN_MOTION_DOT': 0.3267113,
   'MEAN_MOTION_DDOT': 1.2458e-05,
   'SEMIMAJOR_AXIS': 6534.584,
   'PERIOD': 87.617,
   'APOAPSIS': 158.843,
   'PERIAPSIS': 154.056,
   'OBJECT_TYPE': 'PAYLOAD',
   'RCS_SIZE': 'LARGE',
   'COUNTRY_CODE': 'US',
   'LAUNCH_DATE': '2019-05-24',
   'SITE': 'AFETR',
   'DECAY_DATE': '2021-09-26',
   'DECAYED': 1,
   'FILE': 3129087,
   'GP_ID': 185524941,
   'TLE_LINE0': '0 STARLINK-76',
   'TLE_LINE1': '1 44287U 19029BE  21269.58650490  .32671130  12458-4  14077-2 0  9991',
   'TLE_LINE2': '2 44287  52.9578 116.7260 0003663  96.3451 319.5267 16.43523148132637'},
  'launch': '5eb87d30ffd86e000604b378',
  'version': 'v0.9',
  'height_km': None,
  'latitude': None,
  'longitude': None,
  'velocity_kms': None,
  'id': '5eed770f096e590006985610'},
 {'spaceTrack': {'CCSDS_OMM_VERS': '2.0',
   'COMMENT': 'GENERATED VIA SPACE-TRACK.ORG API',
   'CREATION_DATE': '2020-09-02T18:57:38',
   'ORIGINATOR': '18 SPCS',
   'OBJECT_NAME': 'STARLINK-23',
   'OBJECT_ID': '2019-029C',
   'CENTER_NAME': 'EARTH',
   'REF_FRAME': 'TEME',
   'TIME_SYSTEM': 'UTC',
   'MEAN_ELEMENT_THEORY': 'SGP4',
   'EPOCH': '2020-09-02T05:50:39.789312',
   'MEAN_MOTION': 16.40837491,
   'ECCENTRICITY': 0.0004551,
   'INCLINATION': 52.9945,
   'RA_OF_ASC_NODE': 186.9776,
   'ARG_OF_PERICENTER': 271.9057,
   'MEAN_ANOMALY': 198.4437,
   'EPHEMERIS_TYPE': 0,
   'CLASSIFICATION_TYPE': 'U',
   'NORAD_CAT_ID': 44237,
   'ELEMENT_SET_NO': 999,
   'REV_AT_EPOCH': 7120,
   'BSTAR': 0.0015299,
   'MEAN_MOTION_DOT': 0.23336896,
   'MEAN_MOTION_DDOT': 1.2391e-05,
   'SEMIMAJOR_AXIS': 6541.712,
   'PERIOD': 87.76,
   'APOAPSIS': 166.554,
   'PERIAPSIS': 160.6,
   'OBJECT_TYPE': 'PAYLOAD',
   'RCS_SIZE': 'LARGE',
   'COUNTRY_CODE': 'US',
   'LAUNCH_DATE': '2019-05-24',
   'SITE': 'AFETR',
   'DECAY_DATE': '2020-09-02',
   'DECAYED': 1,
   'FILE': 2813120,
   'GP_ID': 160599026,
   'TLE_LINE0': '0 STARLINK-23',
   'TLE_LINE1': '1 44237U 19029C   20246.24351608 +.23336896 +12391-4 +15299-2 0  9992',
   'TLE_LINE2': '2 44237 052.9945 186.9776 0004551 271.9057 198.4437 16.40837491071205'},
  'launch': '5eb87d30ffd86e000604b378',
  'version': 'v0.9',
  'height_km': None,
  'latitude': None,
  'longitude': None,
  'velocity_kms': None,
  'id': '5eed770f096e590006985611'},
 {'spaceTrack': {'CCSDS_OMM_VERS': '2.0',
   'COMMENT': 'GENERATED VIA SPACE-TRACK.ORG API',
   'CREATION_DATE': '2020-08-09T19:11:44',
   'ORIGINATOR': '18 SPCS',
   'OBJECT_NAME': 'STARLINK-22',
   'OBJECT_ID': '2019-029B',
   'CENTER_NAME': 'EARTH',
   'REF_FRAME': 'TEME',
   'TIME_SYSTEM': 'UTC',
   'MEAN_ELEMENT_THEORY': 'SGP4',
   'EPOCH': '2020-08-09T13:16:33.420576',
   'MEAN_MOTION': 16.42066597,
   'ECCENTRICITY': 0.0004178,
   'INCLINATION': 52.9807,
   'RA_OF_ASC_NODE': 260.6619,
   'ARG_OF_PERICENTER': 316.6235,
   'MEAN_ANOMALY': 43.5158,
   'EPHEMERIS_TYPE': 0,
   'CLASSIFICATION_TYPE': 'U',
   'NORAD_CAT_ID': 44236,
   'ELEMENT_SET_NO': 999,
   'REV_AT_EPOCH': 6921,
   'BSTAR': 0.0017311,
   'MEAN_MOTION_DOT': 0.30875389,
   'MEAN_MOTION_DDOT': 1.2472e-05,
   'SEMIMAJOR_AXIS': 6538.447,
   'PERIOD': 87.694,
   'APOAPSIS': 163.044,
   'PERIAPSIS': 157.581,
   'OBJECT_TYPE': 'PAYLOAD',
   'RCS_SIZE': 'LARGE',
   'COUNTRY_CODE': 'US',
   'LAUNCH_DATE': '2019-05-24',
   'SITE': 'AFETR',
   'DECAY_DATE': '2020-08-09',
   'DECAYED': 1,
   'FILE': 2798784,
   'GP_ID': 159069947,
   'TLE_LINE0': '0 STARLINK-22',
   'TLE_LINE1': '1 44236U 19029B   20222.55316459 +.30875389 +12472-4 +17311-2 0  9994',
   'TLE_LINE2': '2 44236 052.9807 260.6619 0004178 316.6235 043.5158 16.42066597069218'},
  'launch': '5eb87d30ffd86e000604b378',
  'version': 'v0.9',
  'height_km': None,
  'latitude': None,
  'longitude': None,
  'velocity_kms': None,
  'id': '5eed770f096e590006985612'},
 {'spaceTrack': {'CCSDS_OMM_VERS': '2.0',
   'COMMENT': 'GENERATED VIA SPACE-TRACK.ORG API',
   'CREATION_DATE': '2021-04-10T10:26:10',
   'ORIGINATOR': '18 SPCS',
   'OBJECT_NAME': 'STARLINK-26',
   'OBJECT_ID': '2019-029F',
   'CENTER_NAME': 'EARTH',
   'REF_FRAME': 'TEME',
   'TIME_SYSTEM': 'UTC',
   'MEAN_ELEMENT_THEORY': 'SGP4',
   'EPOCH': '2021-04-10T10:04:00.819552',
   'MEAN_MOTION': 16.41561846,
   'ECCENTRICITY': 0.0004843,
   'INCLINATION': 52.9634,
   'RA_OF_ASC_NODE': 161.2403,
   'ARG_OF_PERICENTER': 7.8568,
   'MEAN_ANOMALY': 353.8836,
   'EPHEMERIS_TYPE': 0,
   'CLASSIFICATION_TYPE': 'U',
   'NORAD_CAT_ID': 44240,
   'ELEMENT_SET_NO': 999,
   'REV_AT_EPOCH': 10601,
   'BSTAR': 0.0012328,
   'MEAN_MOTION_DOT': 0.20637293,
   'MEAN_MOTION_DDOT': 1.2492e-05,
   'SEMIMAJOR_AXIS': 6539.788,
   'PERIOD': 87.721,
   'APOAPSIS': 164.82,
   'PERIAPSIS': 158.486,
   'OBJECT_TYPE': 'PAYLOAD',
   'RCS_SIZE': 'LARGE',
   'COUNTRY_CODE': 'US',
   'LAUNCH_DATE': '2019-05-24',
   'SITE': 'AFETR',
   'DECAY_DATE': '2021-04-10',
   'DECAYED': 1,
   'FILE': 3013724,
   'GP_ID': 175267022,
   'TLE_LINE0': '0 STARLINK-26',
   'TLE_LINE1': '1 44240U 19029F   21100.41945393  .20637293  12492-4  12328-2 0  9999',
   'TLE_LINE2': '2 44240  52.9634 161.2403 0004843   7.8568 353.8836 16.41561846106011'},
  'launch': '5eb87d30ffd86e000604b378',
  'version': 'v0.9',
  'height_km': None,
  'latitude': None,
  'longitude': None,
  'velocity_kms': None,
  'id': '5eed770f096e590006985613'},
 {'spaceTrack': {'CCSDS_OMM_VERS': '2.0',
   'COMMENT': 'GENERATED VIA SPACE-TRACK.ORG API',
   'CREATION_DATE': '2020-09-26T00:36:08',
   'ORIGINATOR': '18 SPCS',
   'OBJECT_NAME': 'STARLINK-27',
   'OBJECT_ID': '2019-029G',
   'CENTER_NAME': 'EARTH',
   'REF_FRAME': 'TEME',
   'TIME_SYSTEM': 'UTC',
   'MEAN_ELEMENT_THEORY': 'SGP4',
   'EPOCH': '2020-09-25T23:58:24.572928',
   'MEAN_MOTION': 16.44528987,
   'ECCENTRICITY': 0.0005013,
   'INCLINATION': 52.9952,
   'RA_OF_ASC_NODE': 62.9276,
   'ARG_OF_PERICENTER': 292.5876,
   'MEAN_ANOMALY': 67.3813,
   'EPHEMERIS_TYPE': 0,
   'CLASSIFICATION_TYPE': 'U',
   'NORAD_CAT_ID': 44241,
   'ELEMENT_SET_NO': 999,
   'REV_AT_EPOCH': 7502,
   'BSTAR': 0.00090269,
   'MEAN_MOTION_DOT': 0.27533098,
   'MEAN_MOTION_DDOT': 1.2522e-05,
   'SEMIMAJOR_AXIS': 6531.919,
   'PERIOD': 87.563,
   'APOAPSIS': 157.058,
   'PERIAPSIS': 150.509,
   'OBJECT_TYPE': 'PAYLOAD',
   'RCS_SIZE': 'LARGE',
   'COUNTRY_CODE': 'US',
   'LAUNCH_DATE': '2019-05-24',
   'SITE': 'AFETR',
   'DECAY_DATE': '2020-09-26',
   'DECAYED': 1,
   'FILE': 2834145,
   'GP_ID': 162165742,
   'TLE_LINE0': '0 STARLINK-27',
   'TLE_LINE1': '1 44241U 19029G   20269.99889552  .27533098  12522-4  90269-3 0  9992',
   'TLE_LINE2': '2 44241  52.9952  62.9276 0005013 292.5876  67.3813 16.44528987 75025'},
  'launch': '5eb87d30ffd86e000604b378',
  'version': 'v0.9',
  'height_km': None,
  'latitude': None,
  'longitude': None,
  'velocity_kms': None,
  'id': '5eed770f096e590006985614'},
 {'spaceTrack': {'CCSDS_OMM_VERS': '2.0',
   'COMMENT': 'GENERATED VIA SPACE-TRACK.ORG API',
   'CREATION_DATE': '2020-08-23T05:06:09',
   'ORIGINATOR': '18 SPCS',
   'OBJECT_NAME': 'STARLINK-58',
   'OBJECT_ID': '2019-029AM',
   'CENTER_NAME': 'EARTH',
   'REF_FRAME': 'TEME',
   'TIME_SYSTEM': 'UTC',
   'MEAN_ELEMENT_THEORY': 'SGP4',
   'EPOCH': '2020-08-23T03:09:46.298304',
   'MEAN_MOTION': 16.49769755,
   'ECCENTRICITY': 0.0010115,
   'INCLINATION': 53.006,
   'RA_OF_ASC_NODE': 191.4104,
   'ARG_OF_PERICENTER': 188.7689,
   'MEAN_ANOMALY': 171.4914,
   'EPHEMERIS_TYPE': 0,
   'CLASSIFICATION_TYPE': 'U',
   'NORAD_CAT_ID': 44270,
   'ELEMENT_SET_NO': 999,
   'REV_AT_EPOCH': 7027,
   'BSTAR': 0.0001307,
   'MEAN_MOTION_DOT': 0.12051508,
   'MEAN_MOTION_DDOT': 1.2468e-05,
   'SEMIMAJOR_AXIS': 6518.078,
   'PERIOD': 87.284,
   'APOAPSIS': 146.536,
   'PERIAPSIS': 133.35,
   'OBJECT_TYPE': 'PAYLOAD',
   'RCS_SIZE': 'LARGE',
   'COUNTRY_CODE': 'US',
   'LAUNCH_DATE': '2019-05-24',
   'SITE': 'AFETR',
   'DECAY_DATE': '2020-08-23',
   'DECAYED': 1,
   'FILE': 2806775,
   'GP_ID': 159934884,
   'TLE_LINE0': '0 STARLINK-58',
   'TLE_LINE1': '1 44270U 19029AM  20236.13178586  .12051508  12468-4  13070-3 0  9991',
   'TLE_LINE2': '2 44270  53.0060 191.4104 0010115 188.7689 171.4914 16.49769755 70270'},
  'launch': '5eb87d30ffd86e000604b378',
  'version': 'v0.9',
  'height_km': None,
  'latitude': None,
  'longitude': None,
  'velocity_kms': None,
  'id': '5eed770f096e590006985615'},
 {'spaceTrack': {'CCSDS_OMM_VERS': '2.0',
   'COMMENT': 'GENERATED VIA SPACE-TRACK.ORG API',
   'CREATION_DATE': '2020-08-29T09:36:09',
   'ORIGINATOR': '18 SPCS',
   'OBJECT_NAME': 'TINTIN A',
   'OBJECT_ID': '2018-020B',
   'CENTER_NAME': 'EARTH',
   'REF_FRAME': 'TEME',
   'TIME_SYSTEM': 'UTC',
   'MEAN_ELEMENT_THEORY': 'SGP4',
   'EPOCH': '2020-08-29T07:40:05.480832',
   'MEAN_MOTION': 16.40201759,
   'ECCENTRICITY': 0.0015282,
   'INCLINATION': 97.4245,
   'RA_OF_ASC_NODE': 260.1382,
   'ARG_OF_PERICENTER': 265.467,
   'MEAN_ANOMALY': 95.5903,
   'EPHEMERIS_TYPE': 0,
   'CLASSIFICATION_TYPE': 'U',
   'NORAD_CAT_ID': 43216,
   'ELEMENT_SET_NO': 999,
   'REV_AT_EPOCH': 14020,
   'BSTAR': 0.0016505,
   'MEAN_MOTION_DOT': 0.26379725,
   'MEAN_MOTION_DDOT': 2.565e-06,
   'SEMIMAJOR_AXIS': 6543.402,
   'PERIOD': 87.794,
   'APOAPSIS': 175.267,
   'PERIAPSIS': 155.268,
   'OBJECT_TYPE': 'PAYLOAD',
   'RCS_SIZE': 'LARGE',
   'COUNTRY_CODE': 'US',
   'LAUNCH_DATE': '2018-02-22',
   'SITE': 'AFWTR',
   'DECAY_DATE': '2020-08-29',
   'DECAYED': 1,
   'FILE': 2810670,
   'GP_ID': 160342842,
   'TLE_LINE0': '0 TINTIN A',
   'TLE_LINE1': '1 43216U 18020B   20242.31950788  .26379725  25650-5  16505-2 0  9991',
   'TLE_LINE2': '2 43216  97.4245 260.1382 0015282 265.4670  95.5903 16.40201759140202'},
  'launch': '5eb87d14ffd86e000604b361',
  'version': 'prototype',
  'height_km': None,
  'latitude': None,
  'longitude': None,
  'velocity_kms': None,
  'id': '5eed770f096e590006985616'},
 {'spaceTrack': {'CCSDS_OMM_VERS': '2.0',
   'COMMENT': 'GENERATED VIA SPACE-TRACK.ORG API',
   'CREATION_DATE': '2020-08-08T05:36:08',
   'ORIGINATOR': '18 SPCS',
   'OBJECT_NAME': 'TINTIN B',
   'OBJECT_ID': '2018-020C',
   'CENTER_NAME': 'EARTH',
   'REF_FRAME': 'TEME',
   'TIME_SYSTEM': 'UTC',
   'MEAN_ELEMENT_THEORY': 'SGP4',
   'EPOCH': '2020-08-08T00:27:11.780640',
   'MEAN_MOTION': 16.48446726,
   'ECCENTRICITY': 0.0015584,
   'INCLINATION': 97.4319,
   'RA_OF_ASC_NODE': 238.058,
   'ARG_OF_PERICENTER': 250.5191,
   'MEAN_ANOMALY': 169.7925,
   'EPHEMERIS_TYPE': 0,
   'CLASSIFICATION_TYPE': 'U',
   'NORAD_CAT_ID': 43217,
   'ELEMENT_SET_NO': 999,
   'REV_AT_EPOCH': 13685,
   'BSTAR': 0.00047877,
   'MEAN_MOTION_DOT': 0.36665659,
   'MEAN_MOTION_DDOT': 2.6093e-06,
   'SEMIMAJOR_AXIS': 6521.566,
   'PERIOD': 87.354,
   'APOAPSIS': 153.594,
   'PERIAPSIS': 133.267,
   'OBJECT_TYPE': 'PAYLOAD',
   'RCS_SIZE': 'LARGE',
   'COUNTRY_CODE': 'US',
   'LAUNCH_DATE': '2018-02-22',
   'SITE': 'AFWTR',
   'DECAY_DATE': '2020-08-08',
   'DECAYED': 1,
   'FILE': 2797813,
   'GP_ID': 158988627,
   'TLE_LINE0': '0 TINTIN B',
   'TLE_LINE1': '1 43217U 18020C   20221.01888635  .36665659  26093-5  47877-3 0  9991',
   'TLE_LINE2': '2 43217  97.4319 238.0580 0015584 250.5191 169.7925 16.48446726136854'},
  'launch': '5eb87d14ffd86e000604b361',
  'version': 'prototype',
  'height_km': None,
  'latitude': None,
  'longitude': None,
  'velocity_kms': None,
  'id': '5eed770f096e590006985617'},
 {'spaceTrack': {'CCSDS_OMM_VERS': '2.0',
   'COMMENT': 'GENERATED VIA SPACE-TRACK.ORG API',
   'CREATION_DATE': '2021-06-26T08:46:10',
   'ORIGINATOR': '18 SPCS',
   'OBJECT_NAME': 'STARLINK-68',
   'OBJECT_ID': '2019-029AW',
   'CENTER_NAME': 'EARTH',
   'REF_FRAME': 'TEME',
   'TIME_SYSTEM': 'UTC',
   'MEAN_ELEMENT_THEORY': 'SGP4',
   'EPOCH': '2021-06-26T07:23:35.632320',
   'MEAN_MOTION': 16.34670081,
   'ECCENTRICITY': 0.0004973,
   'INCLINATION': 52.9689,
   'RA_OF_ASC_NODE': 175.4485,
   'ARG_OF_PERICENTER': 244.1786,
   'MEAN_ANOMALY': 116.152,
   'EPHEMERIS_TYPE': 0,
   'CLASSIFICATION_TYPE': 'U',
   'NORAD_CAT_ID': 44279,
   'ELEMENT_SET_NO': 999,
   'REV_AT_EPOCH': 11756,
   'BSTAR': 0.002711,
   'MEAN_MOTION_DOT': 0.20332303,
   'MEAN_MOTION_DDOT': 1.2183e-05,
   'SEMIMAJOR_AXIS': 6558.156,
   'PERIOD': 88.091,
   'APOAPSIS': 183.283,
   'PERIAPSIS': 176.76,
   'OBJECT_TYPE': 'PAYLOAD',
   'RCS_SIZE': 'LARGE',
   'COUNTRY_CODE': 'US',
   'LAUNCH_DATE': '2019-05-24',
   'SITE': 'AFETR',
   'DECAY_DATE': '2021-06-26',
   'DECAYED': 1,
   'FILE': 3063138,
   'GP_ID': 179775363,
   'TLE_LINE0': '0 STARLINK-68',
   'TLE_LINE1': '1 44279U 19029AW  21177.30805130  .20332303  12183-4  27110-2 0  9993',
   'TLE_LINE2': '2 44279  52.9689 175.4485 0004973 244.1786 116.1520 16.34670081117568'},
  'launch': '5eb87d30ffd86e000604b378',
  'version': 'v0.9',
  'height_km': None,
  'latitude': None,
  'longitude': None,
  'velocity_kms': None,
  'id': '5eed770f096e590006985618'},
 {'spaceTrack': {'CCSDS_OMM_VERS': '2.0',
   'COMMENT': 'GENERATED VIA SPACE-TRACK.ORG API',
   'CREATION_DATE': '2020-10-01T07:56:08',
   'ORIGINATOR': '18 SPCS',
   'OBJECT_NAME': 'STARLINK-31',
   'OBJECT_ID': '2019-029A',
   'CENTER_NAME': 'EARTH',
   'REF_FRAME': 'TEME',
   'TIME_SYSTEM': 'UTC',
   'MEAN_ELEMENT_THEORY': 'SGP4',
   'EPOCH': '2020-10-01T07:31:19.437888',
   'MEAN_MOTION': 16.46847225,
   'ECCENTRICITY': 0.0009041,
   'INCLINATION': 52.9736,
   'RA_OF_ASC_NODE': 36.3928,
   'ARG_OF_PERICENTER': 295.9879,
   'MEAN_ANOMALY': 160.3065,
   'EPHEMERIS_TYPE': 0,
   'CLASSIFICATION_TYPE': 'U',
   'NORAD_CAT_ID': 44235,
   'ELEMENT_SET_NO': 999,
   'REV_AT_EPOCH': 7697,
   'BSTAR': 0.00018159,
   'MEAN_MOTION_DOT': 0.09808971,
   'MEAN_MOTION_DDOT': 1.2623e-05,
   'SEMIMAJOR_AXIS': 6525.788,
   'PERIOD': 87.439,
   'APOAPSIS': 153.553,
   'PERIAPSIS': 141.753,
   'OBJECT_TYPE': 'PAYLOAD',
   'RCS_SIZE': 'LARGE',
   'COUNTRY_CODE': 'US',
   'LAUNCH_DATE': '2019-05-24',
   'SITE': 'AFETR',
   'DECAY_DATE': '2020-10-01',
   'DECAYED': 1,
   'FILE': 2839167,
   'GP_ID': 162539263,
   'TLE_LINE0': '0 STARLINK-31',
   'TLE_LINE1': '1 44235U 19029A   20275.31341942  .09808971  12623-4  18159-3 0  9999',
   'TLE_LINE2': '2 44235  52.9736  36.3928 0009041 295.9879 160.3065 16.46847225 76971'},
  'launch': '5eb87d30ffd86e000604b378',
  'version': 'v0.9',
  'height_km': None,
  'latitude': None,
  'longitude': None,
  'velocity_kms': None,
  'id': '5eed770f096e590006985619'},
 {'spaceTrack': {'CCSDS_OMM_VERS': '2.0',
   'COMMENT': 'GENERATED VIA SPACE-TRACK.ORG API',
   'CREATION_DATE': '2020-08-21T07:56:08',
   'ORIGINATOR': '18 SPCS',
   'OBJECT_NAME': 'STARLINK-28',
   'OBJECT_ID': '2019-029H',
   'CENTER_NAME': 'EARTH',
   'REF_FRAME': 'TEME',
   'TIME_SYSTEM': 'UTC',
   'MEAN_ELEMENT_THEORY': 'SGP4',
   'EPOCH': '2020-08-21T07:11:00.591360',
   'MEAN_MOTION': 16.52223162,
   'ECCENTRICITY': 0.000603,
   'INCLINATION': 52.9881,

In [ ]:
#convert the output from the API into a dataframe
df = pd.DataFrame(satellites)
# The SpaceTrack data is nested inside each satellite JSON. Unnesting the spacetrack data

if 'spaceTrack' in df.columns:
    # Extract the nested spaceTrack dictionaries into separate columns
    space_track_df = pd.json_normalize(df['spaceTrack'])
    
    # Drop the original spaceTrack column 
    df = df.drop('spaceTrack', axis=1)
    
    # Combine the two dataframes
    df = pd.concat([df, space_track_df], axis=1)

# Now I have a DataFrame with each satellite as a row and each key from JSON as a column

df

,launch,version,height_km,latitude,longitude,velocity_kms,id,CCSDS_OMM_VERS,COMMENT,CREATION_DATE,...,COUNTRY_CODE,LAUNCH_DATE,SITE,DECAY_DATE,DECAYED,FILE,GP_ID,TLE_LINE0,TLE_LINE1,TLE_LINE2
0,5eb87d30ffd86e000604b378,v0.9,NaN,NaN,NaN,NaN,5eed770f096e59000698560d,2.0,GENERATED VIA SPACE-TRACK.ORG API,2020-10-13T04:16:08,...,US,2019-05-24,AFETR,2020-10-13,1,2850561,163365918,0 STARLINK-30,1 44244U 19029K 20287.12291165 .47180237 1...,2 44244 52.9708 332.0356 0003711 120.7278 242...
1,5eb87d30ffd86e000604b378,v0.9,NaN,NaN,NaN,NaN,5eed770f096e59000698560e,2.0,GENERATED VIA SPACE-TRACK.ORG API,2020-09-28T19:26:08,...,US,2019-05-24,AFETR,2020-09-29,1,2837086,162391575,0 STARLINK-74,1 44293U 19029BL 20272.77440637 .11359350 1...,2 44293 52.9971 48.1405 0002076 323.1313 37...
2,5eb87d30ffd86e000604b378,v0.9,NaN,NaN,NaN,NaN,5eed770f096e59000698560f,2.0,GENERATED VIA SPACE-TRACK.ORG API,2020-10-13T17:46:09,...,US,2019-05-24,AFETR,2020-10-13,1,2851295,163381397,0 STARLINK-29,1 44243U 19029J 20287.71504568 .11982673 1...,2 44243 52.9786 228.8138 0008105 330.1078 31...
3,5eb87d30ffd86e000604b378,v0.9,NaN,NaN,NaN,NaN,5eed770f096e590006985610,2.0,GENERATED VIA SPACE-TRACK.ORG API,2021-09-26T14:36:11,...,US,2019-05-24,AFETR,2021-09-26,1,3129087,185524941,0 STARLINK-76,1 44287U 19029BE 21269.58650490 .32671130 1...,2 44287 52.9578 116.7260 0003663 96.3451 319...
4,5eb87d30ffd86e000604b378,v0.9,NaN,NaN,NaN,NaN,5eed770f096e590006985611,2.0,GENERATED VIA SPACE-TRACK.ORG API,2020-09-02T18:57:38,...,US,2019-05-24,AFETR,2020-09-02,1,2813120,160599026,0 STARLINK-23,1 44237U 19029C 20246.24351608 +.23336896 +1...,2 44237 052.9945 186.9776 0004551 271.9057 198...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3521,None,None,355.305350,44.268273,137.300802,7.700996,63655b77358d5951a1c69dd0,2.0,GENERATED VIA SPACE-TRACK.ORG API,2022-11-30T17:18:05,...,US,2022-10-28,AFWTR,None,0,3675646,219177338,0 STARLINK-5186,1 54177U 22141W 22334.58335648 .00048875 0...,2 54177 53.2167 337.9278 0003831 6.8795 344...
3522,None,None,353.712986,33.722400,153.947639,7.700405,63655b77358d5951a1c69dfa,2.0,GENERATED VIA SPACE-TRACK.ORG API,2022-11-30T17:18:05,...,US,2022-10-28,AFWTR,None,0,3675646,219178207,0 STARLINK-5205,1 54202U 22141AX 22334.58335648 -.00044287 0...,2 54202 53.2156 337.8864 0003705 4.5467 3...
3523,None,None,355.632656,44.561516,136.668403,7.700673,63655b77358d5951a1c69e37,2.0,GENERATED VIA SPACE-TRACK.ORG API,2022-11-30T17:18:05,...,US,2022-10-28,AFWTR,None,0,3675646,219177167,0 STARLINK-5117,1 54172U 22141R 22334.58335648 -.00074020 0...,2 54172 53.2159 337.9243 0004424 3.2523 347...
3524,None,None,354.996912,40.755340,143.873451,7.700481,63655b77358d5951a1c69e39,2.0,GENERATED VIA SPACE-TRACK.ORG API,2022-11-30T17:18:05,...,US,2022-10-28,AFWTR,None,0,3675646,219177524,0 STARLINK-5162,1 54184U 22141AD 22334.58335648 -.00088576 0...,2 54184 53.2152 337.9079 0004143 1.3558 356...
3525,None,None,355.396192,44.069184,137.731004,7.700827,63655b77358d5951a1c69e41,2.0,GENERATED VIA SPACE-TRACK.ORG API,2022-11-30T17:18:05,...,US,2022-10-28,AFWTR,None,0,3675646,219178033,0 STARLINK-5122,1 54179U 22141Y 22334.58335648 -.00060135 0...,2 54179 53.2161 337.9252 0003828 2.9089 349...

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3526 entries, 0 to 3525
Data columns (total 48 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   launch               3215 non-null   object
 1   version              3215 non-null   object
 2   height_km            3268 non-null   float64
 3   latitude             3268 non-null   float64
 4   longitude            3268 non-null   float64
 5   velocity_kms         3268 non-null   float64
 6   id                   3526 non-null   object
 7   CCSDS_OMM_VERS       3526 non-null   object
 8   COMMENT              3526 non-null   object
 9   CREATION_DATE        3526 non-null   object
 10  ORIGINATOR           3526 non-null   object
 11  OBJECT_NAME          3526 non-null   object
 12  OBJECT_ID            3526 non-null   object
 13  CENTER_NAME          3526 non-null   object
 14  REF_FRAME            3526 non-null   object
 15  TIME_SYSTEM          3526 non-null   object
 16  MEAN_ELEMENT_THEORY  3526 non-null   object
 17  EPOCH                3526 non-null   object
 18  MEAN_MOTION          3526 non-null   float64
 19  ECCENTRICITY         3526 non-null   float64
 20  INCLINATION          3526 non-null   float64
 21  RA_OF_ASC_NODE       3526 non-null   float64
 22  ARG_OF_PERICENTER    3526 non-null   float64
 23  MEAN_ANOMALY         3526 non-null   float64
 24  EPHEMERIS_TYPE       3526 non-null   int64
 25  CLASSIFICATION_TYPE  3526 non-null   object
 26  NORAD_CAT_ID         3526 non-null   int64
 27  ELEMENT_SET_NO       3526 non-null   int64
 28  REV_AT_EPOCH         3526 non-null   int64
 29  BSTAR                3526 non-null   float64
 30  MEAN_MOTION_DOT      3526 non-null   float64
 31  MEAN_MOTION_DDOT     3526 non-null   float64
 32  SEMIMAJOR_AXIS       3526 non-null   float64
 33  PERIOD               3526 non-null   float64
 34  APOAPSIS             3526 non-null   float64
 35  PERIAPSIS            3526 non-null   float64
 36  OBJECT_TYPE          3526 non-null   object
 37  RCS_SIZE             3515 non-null   object
 38  COUNTRY_CODE         3521 non-null   object
 39  LAUNCH_DATE          3521 non-null   object
 40  SITE                 3521 non-null   object
 41  DECAY_DATE           258 non-null    object
 42  DECAYED              3526 non-null   int64
 43  FILE                 3526 non-null   int64
 44  GP_ID                3526 non-null   int64
 45  TLE_LINE0            3526 non-null   object
 46  TLE_LINE1            3526 non-null   object
 47  TLE_LINE2            3526 non-null   object
dtypes: float64(17), int64(7), object(24)
memory usage: 1.3+ MB

In [11]:
df.tail()

,launch,version,height_km,latitude,longitude,velocity_kms,id,CCSDS_OMM_VERS,COMMENT,CREATION_DATE,...,COUNTRY_CODE,LAUNCH_DATE,SITE,DECAY_DATE,DECAYED,FILE,GP_ID,TLE_LINE0,TLE_LINE1,TLE_LINE2
3521,None,None,355.305350,44.268273,137.300802,7.700996,63655b77358d5951a1c69dd0,2.0,GENERATED VIA SPACE-TRACK.ORG API,2022-11-30T17:18:05,...,US,2022-10-28,AFWTR,None,0,3675646,219177338,0 STARLINK-5186,1 54177U 22141W 22334.58335648 .00048875 0...,2 54177 53.2167 337.9278 0003831 6.8795 344...
3522,None,None,353.712986,33.722400,153.947639,7.700405,63655b77358d5951a1c69dfa,2.0,GENERATED VIA SPACE-TRACK.ORG API,2022-11-30T17:18:05,...,US,2022-10-28,AFWTR,None,0,3675646,219178207,0 STARLINK-5205,1 54202U 22141AX 22334.58335648 -.00044287 0...,2 54202 53.2156 337.8864 0003705 4.5467 3...
3523,None,None,355.632656,44.561516,136.668403,7.700673,63655b77358d5951a1c69e37,2.0,GENERATED VIA SPACE-TRACK.ORG API,2022-11-30T17:18:05,...,US,2022-10-28,AFWTR,None,0,3675646,219177167,0 STARLINK-5117,1 54172U 22141R 22334.58335648 -.00074020 0...,2 54172 53.2159 337.9243 0004424 3.2523 347...
3524,None,None,354.996912,40.755340,143.873451,7.700481,63655b77358d5951a1c69e39,2.0,GENERATED VIA SPACE-TRACK.ORG API,2022-11-30T17:18:05,...,US,2022-10-28,AFWTR,None,0,3675646,219177524,0 STARLINK-5162,1 54184U 22141AD 22334.58335648 -.00088576 0...,2 54184 53.2152 337.9079 0004143 1.3558 356...
3525,None,None,355.396192,44.069184,137.731004,7.700827,63655b77358d5951a1c69e41,2.0,GENERATED VIA SPACE-TRACK.ORG API,2022-11-30T17:18:05,...,US,2022-10-28,AFWTR,None,0,3675646,219178033,0 STARLINK-5122,1 54179U 22141Y 22334.58335648 -.00060135 0...,2 54179 53.2161 337.9252 0003828 2.9089 349...

In [18]:
df[['DECAY_DATE','DECAYED','LAUNCH_DATE']]

      DECAY_DATE  DECAYED LAUNCH_DATE
0     2020-10-13        1  2019-05-24
1     2020-09-29        1  2019-05-24
2     2020-10-13        1  2019-05-24
3     2021-09-26        1  2019-05-24
4     2020-09-02        1  2019-05-24
...          ...      ...         ...
3521        None        0  2022-10-28
3522        None        0  2022-10-28
3523        None        0  2022-10-28
3524        None        0  2022-10-28
3525        None        0  2022-10-28

[3526 rows x 3 columns]

In [ ]:
#i want to create a column for days in orbit. First I need to make sure that decay_date and launch_date are actually correct data types
from datetime import datetime