# Ejercicio

El ejercicio consiste en extraer datos de manera automatizada, realizarle las transformaciones necesarias y luego cargarlos en la base de datos ya creada. La idea sería que con una simple ejecución diaria de este código nuestra base de datos de MySQL se vea actualizada.

 - Carga la librería yfinance, ya que es la que contiene información diaria de los precios de la bolsa. 
 
 - Selecciona un ticker (código de empresa), por ejemplo 'MMM' y ejecuta este código para ver qué nos devuelve yfinance, analiza qué variables tenemos, cómo se llaman, qué formato tienen, qué parte de este dataframe nos interesaría, qué transformaciones necesitaría para encajar perfectamente en la tabla Stocks, que es la que vamos a actualizar diariamente
   ```
    dat = yf.Ticker('MMM')
    dat = dat.history(period='1d')
   ```
 - Crea una función extract(), que automatice esta llamada, una transform(), que ponga los formatos de las variables "en su sitio" y que ordene las variables tal y como las llamarás en la función definitiva load().

In [3]:
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, Date, Float, Enum, ForeignKey

from sqlalchemy_utils import database_exists, create_database, drop_database

from sqlalchemy.orm import Session
from sqlalchemy.orm import sessionmaker

import pandas as pd
import datetime as datetime

import pymysql
import tqdm

#!pip install yfinance --upgrade --no-cache-dir
import yfinance as yf

In [14]:
dat = yf.Ticker('MMM')
dat = dat.history(period='1d')
dat

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-04-04 00:00:00-04:00,134.190002,135.312195,126.544998,127.870003,7396905,0.0,0.0

In [13]:
dat = dat.history(period='1d')
dat

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-04-04 00:00:00-04:00,134.190002,135.312195,126.544998,127.730003,7392489,0.0,0.0

## Activamos la conexión con MySQL

Y definimos de nuevo las clases de las tablas, ya que las necesitaremos igualmente

In [4]:
engine = create_engine('mysql+pymysql://root:MYSQL.passw0rd@localhost:3306/Stockify')
Base = declarative_base()

/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/3210753896.py:2: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base = declarative_base()

In [5]:
class Company(Base):
    __tablename__ = 'Company'
    company_code = Column(String(120),primary_key=True)
    security = Column(String(120))
    sec = Column(String(120))
    gics_sector = Column(String(120))
    gics_sub_industry = Column(String(120))
    heads_location = Column(String(120))
    start_date = Column(Date)
    cik = Column(String(120))
    founded = Column(String(120))

In [6]:
class Stocks(Base):
    __tablename__ = 'Stocks'
    stock_id = Column(Integer,primary_key=True)
    company_code = Column(String(120),ForeignKey("Company.company_code"))
    date = Column(Date)
    max_price = Column(Float)
    min_price = Column(Float)
    volume = Column(Float)
    close = Column(Float)
    open = Column(Float)

In [7]:
class user(Base):
    __tablename__ = 'User'
    user_id = Column(Integer,primary_key=True)
    user_name=Column(String(20))
    user_city=Column(String(120))

In [6]:
class transactions(Base):
    __tablename__ = 'Transactions'
    trx_id = Column(Integer,primary_key=True)
    user_id = Column(Integer,ForeignKey("User.user_id"))
    company_code = Column(String(120),ForeignKey("Company.company_code"))
    stock_id = Column(Integer,ForeignKey("Stocks.stock_id"))
    units = Column(Integer)

## Definición de las funciones

primeramente tenemos la lista tickers con los códigos de las empresas que vamos a querer actualizar a diario. A continuación define las 3 funciones.

In [8]:
Session = sessionmaker(bind=engine)
session = Session()

In [22]:
# Listado de los tickers que hay en la carga de datos que hicimos a través de los csv. Vamos a iterar sobre ellos para ver sus
# precios a día de hoy. Algunos ya no existen. 
ticker_list = [
    "AAL", "AAP", "AAPL", "ABBV", "ABC", "ABMD", "ABT", "ACN", "ADBE", "ADI", "ADM", 
    "ADP", "ADSK", "AEE", "AEP", "AES", "AFL", "AIG", "AIZ", "AJG", "AKAM", "ALB", 
    "ALGN", "ALK", "ALL", "ALLE", "AMAT", "AMCR", "AMD", "AME", "AMGN", "AMP", "AMT", 
    "AMZN", "ANET", "ANSS", "ANTM", "AON", "AOS", "APA", "APD", "APH", "APTV", "ARE", 
    "ATO", "ATVI", "AVB", "AVGO", "AVY", "AWK", "AXP", "AZO", "BA", "BAC", "BAX", 
    "BBWI", "BBY", "BDX", "BEN", "BF.B", "BIIB", "BIO", "BK", "BKNG", "BKR", "BLK", 
    "BLL", "BMY", "BR", "BRK.B", "BRO", "BSX", "BWA", "BXP", "C", "CAG", "CAH", 
    "CARR", "CAT", "CB", "CBOE", "CBRE", "CCI", "CCL", "CDAY", "CDNS", "CDW", "CE", 
    "CEG", "CERN", "CF", "CFG", "CHD", "CHRW", "CHTR", "CI", "CINF", "CL", "CLX", 
    "CMA", "CMCSA", "CME", "CMG", "CMI", "CMS", "CNC", "CNP", "COF", "COO", "COP", 
    "COST", "CPB", "CPRT", "CRL", "CRM", "CSCO", "CSX", "CTAS", "CTLT", "CTRA", 
    "CTSH", "CTVA", "CTXS", "CVS", "CVX", "CZR", "D", "DAL", "DD", "DE", "DFS", 
    "DG", "DGX", "DHI", "DHR", "DIS", "DISCA", "DISCK", "DISH", "DLR", "DLTR", "DOV", 
    "DOW", "DPZ", "DRE", "DRI", "DTE", "DUK", "DVA", "DVN", "DXC", "DXCM", "EA", 
    "EBAY", "ECL", "ED", "EFX", "EIX", "EL", "EMN", "EMR", "ENPH", "EOG", "EPAM", 
    "EQIX", "EQR", "ES", "ESS", "ETN", "ETR", "ETSY", "EVRG", "EW", "EXC", "EXPD", 
    "EXPE", "EXR", "F", "FANG", "FAST", "FB", "FBHS", "FCX", "FDS", "FDX", "FE", 
    "FFIV", "FIS", "FISV", "FITB", "FLT", "FMC", "FOX", "FOXA", "FRC", "FRT", "FTNT", 
    "FTV", "GD", "GE", "GILD", "GIS", "GL", "GLW", "GM", "GNRC", "GOOG", "GOOGL", 
    "GPC", "GPN", "GRMN", "GS", "GWW", "HAL", "HAS", "HCA", "HD", "HES", "HIG", 
    "HII", "HLT", "HOLX", "HON", "HPE", "HPQ", "HRL", "HSIC", "HST", "HSY", "HUM", 
    "HWM", "IBM", "ICE", "IDXX", "IEX", "IFF", "ILMN", "INCY", "INTC", "INTU", "IP", 
    "IPG", "IPGP", "IQV", "IR", "IRM", "ISRG", "IT", "ITW", "IVZ", "J", "JBHT", 
    "JCI", "JKHY", "JNJ", "JNPR", "JPM", "K", "KEY", "KEYS", "KIM", "KLAC", "KMB", 
    "KMI", "KMX", "KO", "KR", "L", "LDOS", "LEN", "LH", "LHX", "LIN", "LKQ", "LLY", 
    "LMT", "LNC", "LNT", "LOW", "LRCX", "LUMN", "LUV", "LVS", "LW", "LYB", "LYV", 
    "MA", "MAA", "MAR", "MAS", "MCD", "MCHP", "MCK", "MCO", "MDLZ", "MDT", "MET", 
    "MGM", "MHK", "MKC", "MKTX", "MLM", "MMC", "MMM", "MNST", "MO", "MOH", "MOS", 
    "MPC", "MPWR", "MRK", "MRNA", "MRO", "MS", "MSCI", "MSFT", "MSI", "MTB", "MTCH", 
    "MTD", "MU", "NCLH", "NDAQ", "NDSN", "NEE", "NEM", "NFLX", "NI", "NKE", "NLOK", 
    "NLSN", "NOC", "NOW", "NRG", "NSC", "NTAP", "NTRS", "NUE", "NVDA", "NVR", "NWL", 
    "NWS", "NWSA", "NXPI", "O", "ODFL", "OGN", "OKE", "OMC", "ORCL", "ORLY", "OTIS", 
    "OXY", "PARA", "PAYC", "PAYX", "PBCT", "PCAR", "PEAK", "PEG", "PENN", "PEP", 
    "PFE", "PFG", "PG", "PGR", "PH", "PHM", "PKG", "PKI", "PLD", "PM", "PNC", "PNR", 
    "PNW", "POOL", "PPG", "PPL", "PRU", "PSA", "PSX", "PTC", "PVH", "PWR", "PXD", 
    "PYPL", "QCOM", "QRVO", "RCL", "RE", "REG", "REGN", "RF", "RHI", "RJF", "RL", 
    "RMD", "ROK", "ROL", "ROP", "ROST", "RSG", "RTX", "SBAC", "SBNY", "SBUX", "SCHW", 
    "SEDG", "SEE", "SHW", "SIVB", "SJM", "SLB", "SNA", "SNPS", "SO", "SPG", "SPGI", 
    "SRE", "STE", "STT", "STX", "STZ", "SWK", "SWKS", "SYF", "SYK", "SYY", "T", 
    "TAP", "TDG", "TDY", "TECH", "TEL", "TER", "TFC", "TFX", "TGT", "TJX", "TMO", 
    "TMUS", "TPR", "TRMB", "TROW", "TRV", "TSCO", "TSLA", "TSN", "TT", "TTWO", "TWTR", 
    "TXN", "TXT", "TYL", "UA", "UAA", "UAL", "UDR", "UHS", "ULTA", "UNH", "UNP", 
    "UPS", "URI", "USB", "V", "VFC", "VLO", "VMC", "VNO", "VRSK", "VRSN", "VRTX", 
    "VTR", "VTRS", "VZ", "WAB", "WAT", "WBA", "WDC", "WEC", "WELL", "WFC", "WM", 
    "WMT", "XOM", "XRAY", "XYL", "YUM", "ZBH", "ZBRA", "ZION", "ZTS"
]

In [26]:
def extract(ticker_list, period='1d'):
    df = pd.DataFrame([])  # Creamos dataframe vacío
    for t in ticker_list:
        # llamada a los datos para cada empresa
        ticker = yf.Ticker(t)
        ticker_data = ticker.history(period=period)
        # Añadimos columna con el ticker para identificar los datos
        ticker_data['Ticker'] = t
        # union con el histórico
        df = pd.concat([df, ticker_data])
    return df

In [27]:
result_df = extract(ticker_list, period='1d')

$ABC: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/861808736.py:10: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat([df, ticker_data])
$ABMD: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/861808736.py:10: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat([df, ticker_data])
$ANTM: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/861808736.py:10: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat([df, ticker_data])
$ATVI: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/861808736.py:10: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat([df, ticker_data])
$BF.B: possibly delisted; no price data found  (period=1d)
/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/861808736.py:10: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat([df, ticker_data])
$BLL: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/861808736.py:10: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat([df, ticker_data])
$BRK.B: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/861808736.py:10: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat([df, ticker_data])
$CDAY: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/861808736.py:10: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat([df, ticker_data])
$CERN: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/861808736.py:10: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat([df, ticker_data])
$CTLT: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/861808736.py:10: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat([df, ticker_data])
$CTXS: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/861808736.py:10: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat([df, ticker_data])
$DISCA: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/861808736.py:10: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat([df, ticker_data])
$DISCK: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/861808736.py:10: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat([df, ticker_data])
$DISH: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/861808736.py:10: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat([df, ticker_data])
$DRE: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/861808736.py:10: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat([df, ticker_data])
$FB: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/861808736.py:10: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat([df, ticker_data])
$FBHS: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/861808736.py:10: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat([df, ticker_data])
$FISV: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/861808736.py:10: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat([df, ticker_data])
$FLT: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/861808736.py:10: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat([df, ticker_data])
$FRC: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/861808736.py:10: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat([df, ticker_data])
$MRO: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/861808736.py:10: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat([df, ticker_data])
$NLOK: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/861808736.py:10: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat([df, ticker_data])
$NLSN: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/861808736.py:10: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat([df, ticker_data])
$PBCT: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/861808736.py:10: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat([df, ticker_data])
$PEAK: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/861808736.py:10: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat([df, ticker_data])
$PKI: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/861808736.py:10: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat([df, ticker_data])
$PXD: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/861808736.py:10: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat([df, ticker_data])
$RE: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/861808736.py:10: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat([df, ticker_data])
$SIVB: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/861808736.py:10: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat([df, ticker_data])
$TWTR: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
/var/folders/2w/67ngcypn5n73c0m099s75wdc0000gn/T/ipykernel_3018/861808736.py:10: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  df = pd.concat([df, ticker_data])

In [29]:
result_df.head(15)

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Ticker,Adj Close
Date,,,,,,,,,
2025-04-04 00:00:00-04:00,9.210000,9.540000,8.500000,9.520000,99694299.0,0.0,0.0,AAL,NaN
2025-04-04 00:00:00-04:00,35.790001,36.917599,34.509998,35.299999,2184493.0,0.0,0.0,AAP,NaN
2025-04-04 00:00:00-04:00,193.925003,199.880005,187.345001,191.270004,99005882.0,0.0,0.0,AAPL,NaN
2025-04-04 00:00:00-04:00,200.000000,199.824997,187.929993,187.929993,8727023.0,0.0,0.0,ABBV,NaN
2025-04-04 00:00:00-04:00,131.229996,132.399994,124.000000,125.455002,7568575.0,0.0,0.0,ABT,NaN
2025-04-04 00:00:00-04:00,296.799988,299.049988,287.140015,289.100006,3103868.0,0.0,0.0,ACN,NaN
2025-04-04 00:00:00-04:00,359.000000,361.730011,350.910004,354.179993,4299312.0,0.0,0.0,ADBE,NaN
2025-04-04 00:00:00-04:00,173.919998,176.410004,165.339996,167.470001,6302111.0,0.0,0.0,ADI,NaN
2025-04-04 00:00:00-04:00,45.750000,46.075001,43.009998,43.759998,5059232.0,0.0,0.0,ADM,NaN
2025-04-04 00:00:00-04:00,305.579987,306.000000,288.144989,289.815002,2471492.0,0.0,0.0,ADP,NaN
2025-04-04 00:00:00-04:00,250.110001,252.660004,244.389999,246.797501,2022576.0,0.0,0.0,ADSK,NaN
2025-04-04 00:00:00-04:00,102.480003,102.320000,95.050003,96.110001,2159851.0,0.0,0.0,AEE,NaN
2025-04-04 00:00:00-04:00,110.120003,110.480003,103.915001,105.000000,4848884.0,0.0,0.0,AEP,NaN
2025-04-04 00:00:00-04:00,11.450000,11.430000,10.520000,10.729900,15027702.0,0.0,0.0,AES,NaN
2025-04-04 00:00:00-04:00,109.339996,109.839996,101.820000,102.900002,2130805.0,0.0,0.0,AFL,NaN

In [ ]:
class Stocks(Base):
    __tablename__ = 'Stocks'
    stock_id = Column(Integer,primary_key=True)
    company_code = Column(String(120),ForeignKey("Company.company_code"))
    date = Column(Date)
    max_price = Column(Float)
    min_price = Column(Float)
    volume = Column(Float)
    close = Column(Float)
    open = Column(Float)

In [27]:
def transform(df):
    df_transform = df.copy()
    
    # Realiza las transformaciones necesarias
    
    return df_transform

In [28]:
def load(ticker_list, period,table):

    # Llama a las funciones extract y transform
    
    # En principio el resto de la función load lo podemos dejar igual que cuando alimentamos las tablas por primera vez
    # los cambios deberán venir hechos en transform()
    
    for i, val in enumerate(df_transform.values):
        if table == 'Company':
            rec = Company (
                company_code = val[2],
                security = val[3],
                sec = val[4],
                gics_sector = val[5],
                gics_sub_industry = val[6],
                heads_location = val[7],
                start_date = datetime.datetime.strptime(str(val[8]), "%d/%m/%Y").date(),
                cik = val[9],
                founded = val[10]
            )
        
        elif table == 'Stocks':
            rec = Stocks (
                company_code = val[-1],
                date = val[1], 
                max_price = val[3],
                min_price = val[4],
                volume = val[6],
                close = val[5],
                open = val[2]

            )
        elif table == 'User':
            rec = user (
                user_id = val[0],
                user_name = val[1],
                user_city = val[2]

            )  
        else:
            rec = transactions(
                trx_id = val[0],
                user_id = val[1],
                company_code = val[3],
                stock_id = val[2],
                units = val[4]
                
            )
            
        session.add(rec)
        
    session.commit()

## Insertamos los datos

Llama a `load()` para que se complete el proceso ETL.

Ten cuidado porque si la acción no queda completamente realizada, porque dé error por ejemplo, habrá que hacer `rollback()`, para revertir lo que se quedó sin completar

In [ ]:
period = '1d'
table = 'Stocks'
load(tickers, period, table)